config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("phone.urls"))
]

phone/urls.py
from django.urls import path, include
from . import views
from rest_framework import routers

router = routers.DefaultRouter()

router.register(r"phonemodel", views.PhoneModelViewSet)


urlpatterns = [
    path("", views.PhoneListView.as_view(), name="phone-list-page"),
    path("create-phone", views.phone_form_view, name="phone-form-page"),
    path("create-brand", views.brand_form_view, name="brand-form-page"),
    path("api/", include(router.urls))
]

phone/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django_countries.fields import CountryField


# Create your models here.
class PhoneModel(models.Model):
    phone_brand = models.ForeignKey('Brand', on_delete=models.CASCADE, verbose_name="برند")
    phone_model = models.CharField("مدل تلفن همراه", max_length=300, unique=True)
    price = models.IntegerField("قیمت", default=0, validators=[
        MinValueValidator(1, "قیمت را به درستی وارد بکنید")
    ])
    color = models.CharField("رنگ محصول", max_length=200)
    phone_size = models.FloatField("سایز گوشی همراه", default=0, validators=[
        MinValueValidator(1, " اندازه صفحه نمایش را به درستی وارد کنید ")
    ])
    availability = models.BooleanField("موجود", default=False)
    count = models.IntegerField("تعداد", blank=True, default=0, validators=[
        MinValueValidator(0, "تعداد گوشی ها را به درستی وارد بکنید")
    ])

    creator_country = CountryField("کشورسازنده")

    total_price = models.IntegerField("جمع قیمت محصولات", validators=[
        MinValueValidator(0, "قیمت کل را به درستی وارد بکنید ")
    ])

    def save(self, *args, **kwargs):
        self.total_price = self.price * self.count
        super(PhoneModel, self).save(*args, **kwargs)

    def __str__(self):
        return self.phone_model

    class Meta:
        db_table = 'phone'
        verbose_name = 'گوشی'
        verbose_name_plural = 'گوشی ها'


class Brand(models.Model):
    brand_name = models.CharField("نام برند", max_length=300)
    brand_national = CountryField("ملیت برند")

    def __str__(self):
        return self.brand_name

    class Meta:
        db_table = 'brand'
        verbose_name = 'برند'
        verbose_name_plural = 'برند ها'

phone/forms.py
from django import forms 
from .models import PhoneModel, Brand


class PhoneForm(forms.ModelForm):
    
    class Meta:
        model = PhoneModel
        fields = "__all__"
        
    def clean(self):
        
        # cleaned data variables ---------------------------------------------------------------------------------------+
        
        cleaned_data = super().clean()
        count = cleaned_data.get("count")
        availability = cleaned_data.get("availability")
        phone_model = cleaned_data.get("phone_model")
        color = cleaned_data.get("color")
        creator_country = cleaned_data.get("creator_country")
        
        # end -----------------------------------------------------------------------------------------------------------
        
        # validate for availability ------------------------------------------------------------------------------------+
        
        if availability == True:
            if count == 0:
                self.add_error("count", "باید تعداد محصولات بیشتر از 0 باشد")        
                
        # end -----------------------------------------------------------------------------------------------------------
        
        # validate for existing ----------------------------------------------------------------------------------------+
         
        is_exist = PhoneModel.objects.filter(
            phone_model__iexact = phone_model,
            color__iexact = color,
            creator_country__iexact = creator_country     
        ).exists()
        
        if is_exist:
            raise forms.ValidationError("محصول مورد نظر موجود است")    
        
        # end ------------------------------------------------------------------------------------------------------------    
        return cleaned_data
        
        
class BrandForm(forms.ModelForm):
    
    class Meta:
        model = Brand
        fields = "__all__"

    
    def clean(self):
        cleaned_data = super().clean()
        
        brand_name = cleaned_data.get("brand_name")
        brand_national = cleaned_data.get("brand_national")
        
        is_exist = Brand.objects.filter(
            brand_name__iexact = brand_name,
            brand_national__iexact = brand_national
        ).exists()
        
        if is_exist:
            raise forms.ValidationError("برند مد نظر موجود است، لطفا از میان برند ها انتخاب بکنید.")
        
        return cleaned_data
    

phone/views.py
from django.views.generic.list import ListView
from django.shortcuts import redirect, render
from .models import PhoneModel, Brand
from django.core.exceptions import ValidationError
from django.db.models import F, Q
from .forms import PhoneForm, BrandForm
from rest_framework import viewsets
from .serializers import PhoneModelSerializer, BrandSerializer
from django_tables2 import SingleTableView
from django_tables2 import RequestConfig

from .tables import PhoneTable
# Create your views here.


class PhoneListView(SingleTableView):
    model = PhoneModel
    table_class = PhoneTable
    context_object_name = "phones"
    template_name = 'phone/phones-list.html'
    table_pagination = {
        'per_page': 5
    }
    
    def get_queryset(self):
        queryset = super().get_queryset()

        # self.request.GET
        nationality = self.request.GET.get("nationality")
        same_nationality = self.request.GET.get("same_nationality")
        availability = self.request.GET.get("availability")
        brand_things = self.request.GET.get("brand_things")
        
        # filter based on brand name and phone model ---------------------------------------------------------------------+
        if brand_things:
            brand_things = brand_things.replace("+", " ")
            queryset = queryset.filter(Q(phone_brand__brand_name__iexact=brand_things)|Q(phone_model__icontains=brand_things))
            
        # end -------------------------------------------------------------------------------------------------------------
        
        # filter based on nationality -------------------------------------------------------------------------------------+
        
        if nationality is not None:
            queryset = queryset.filter(phone_brand__brand_national=nationality)
        
        # end --------------------------------------------------------------------------------------------------------------
         
        # filter based on  brand_nationality == creator_country -----------------------------------------------------------+
        
        if same_nationality == "on":
            queryset = queryset.filter(phone_brand__brand_national__iexact = F("creator_country") )
        
        # end --------------------------------------------------------------------------------------------------------------
        
        # only phones that are available ----------------------------------------------------------------------------------+
        
        if availability == "on":
            queryset = queryset.filter(availability=True)
            
        # end --------------------------------------------------------------------------------------------------------------
        
            
        

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        # get nationality's and send it to template
        # ------------------------------------------------------------------------+
        
        list_national = set([x.phone_brand.brand_national for x in PhoneModel.objects.all()])
        context["nationals"] = list_national
        
        # end
        # ---------------------------------------------------------------------------------------------------------------

        return context
    

def phone_form_view(request):
    if request.method == "POST":
        form = PhoneForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("phone-list-page")
    else:
        
        form = PhoneForm()
    all_errors = []
    for field , errors in form.errors.items():
        all_errors.append(errors)
    return render(request, "phone/phone-form.html", {"form": form, "errors": all_errors})

def brand_form_view(request):
    if request.method == "POST":
        form = BrandForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("phone-form-page")
    else:
        form = BrandForm()
    all_errors = []
    for field, errors in form.errors.items():
        all_errors.append(errors)
        
    return render(request, "phone/brand-form.html", {"form": form, "errors": all_errors})


class PhoneModelViewSet(viewsets.ModelViewSet):
    queryset = PhoneModel.objects.all()
    serializer_class = PhoneModelSerializer

phone/templates/phone/brand-form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <style>

            .container {
                display: flex;
                flex-direction: column;
                justify-content: center;
                align-items: center;
                height: 100vh;
                direction: rtl;
            }

            .center {
                width: 30%;
                padding: 20px;
                border: 2px solid green;
                border-radius: 10px;
            }

            .warning {
                border : 1px solid red;
                background-color: rgb(201, 70, 70);
                border-radius: 5px;
                margin-bottom: 10px;
            }

            .form-control{
                display: flex;
                margin-bottom: 10px;
            }

            input {
                flex: 2;
                padding: 5px;
                border: 1px solid green;
                border-radius: 5px;
                margin-right: 5px;
            }

            #id_brand_national {
                flex: 2;
                padding: 5px;
                border: 1px solid green;
                border-radius: 5px;
                margin-right: 5px;
            }
            .form-button {
                display: flex;
                justify-content: flex-end;
            }

    </style>
</head>
<body>
    <div class="container">
        <div class="title">
            <h2>برند جدید را وارد بکنید </h2>
        </div>

        <div class="center">
            <form action="{% url 'brand-form-page' %}" method="post">
                {% csrf_token %}
    
                    {% if form.errors %}
                        <div class="warning">
                            {% for error in errors %}
                                {{ error }}
                            {% endfor %}
                        </div>
                    {% endif %}
    
                    <div class="form-control">
                        {{ form.brand_name.label }}
                        {{ form.brand_name }}
                    </div>
                    
                    <div class="form-control">
                        {{ form.brand_national.label }}
                        {{ form.brand_national }}
                    </div>
                <div class="form-control form-button">
                    <button type="submit">ثبت</button>
                </div>
            </form>
        </div>
    </div>
</body>
</html>

phone/templates/phone/phone-form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <style>


.container {
                display: flex;
                flex-direction: column;
                justify-content: center;
                align-items: center;
                height: 100vh;
                direction: rtl;
            }

            .center {
                width: 30%;
                padding: 20px;
                border: 2px solid green;
                border-radius: 10px;
            }

            .warning {
                border : 1px solid red;
                background-color: rgb(201, 70, 70);
                border-radius: 5px;
                margin-bottom: 10px;
            }

            .form-control{
                display: flex;
                margin-bottom: 10px;
            }

            input {
                flex: 2;
                padding: 5px;
                border: 1px solid green;
                border-radius: 5px;
                margin-right: 5px;
            }

            select {
                flex: 2;
                padding: 5px;
                border: 1px solid green;
                border-radius: 5px;
                margin-right: 5px;
            }
            .form-button {
                display: flex;
                justify-content: flex-end;
            }

            .form-button button:hover {
                border-radius: 10px;
                border-color: green;
                color:green
            }

            .form-button button {
                border-radius: 10px;
                width: 120px;
                height: 35px;
            }

    </style>
</head>
<body>
    
    <div class="container">
        <div class="title">
            <h2>لطفا محصول جدید را وارد بکنید</h2>
        </div>
        <div class="center">
            <form method="post" action="{% url 'phone-form-page' %}">
            
                {% csrf_token %}
                
                {% if form.errors %}
                    <div class="warning">
                       {% for error in errors %}
                        {{ error }}
                       {% endfor %}
                    </div>
                {% endif %}
    
                <div class="form-control">
                    {{ form.phone_brand.label }}
                    {{ form.phone_brand }}
                    <div class="form-button">
                        <button><a href="{% url 'brand-form-page' %}">ساخت برند جدید</a></button>
                    </div>
                </div>
                <div class="form-control">
                    {{ form.phone_model.label }}
                    {{ form.phone_model }}
                </div>
                <div class="form-control">
                    {{ form.price.label }}
                    {{ form.price }}
                </div>
                <div class="form-control">
                    {{ form.color.label }}
                    {{ form.color }}
                </div>
                <div class="form-control">
                    {{ form.phone_size.label }}
                    {{ form.phone_size }}
                </div>
                <div class="form-control">
                    {{ form.availability.label }}
                    {{ form.availability }}
                </div>
                
                <div class="form-control">
                    {{ form.count.label }}
                    {{ form.count }}    
                </div>
                <div class="form-control">
                    {{ form.creator_country.label }}
                    {{ form.creator_country }}
                </div>
                
                <div class="form-button">
                    <button type="submit" style="margin-right: 45%; margin-bottom: 10px;">ثبت</button>
                </div>
            </form>
        </div>
    </div>

</body>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        var countField = document.querySelector('#id_count');
        countField.closest('.form-control').style.display = 'none';
        var availabilityCheckbox = document.querySelector('#id_availability');
        availabilityCheckbox.addEventListener('change', function() {
            if (this.checked) {
                countField.closest('.form-control').style.display = 'block';
            } else {
                countField.closest('.form-control').style.display = 'none';
            }
        });
    });
    </script>
    
</html>

phone/templates/phone/phones-list.html
{% load render_table from django_tables2 %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>phone list</title>
    <link rel="stylesheet" href="{% static 'css/custom-home.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
</head>
<body>
<div class="form">
    <form action="{% url 'phone-list-page' %}" method="get" dir="rtl">

        <label for="">نام برند یا مدل گوشی را وارد بکنید:</label>
        <input type="text" name="brand_things" id="brand_things"/>

        <label for="nationality">ملیت برند را انتخاب بکنید:</label>
        <select name="nationality" id="nationality">
            <option disabled selected value> -- لطفا یک گزینه انتخاب بکنید --</option>
            {% for national in nationals %}
                <option value="{{ national }}">{{ national.name }}</option>
            {% endfor %}
        </select>

        <label for="same_nationality">ملیت با کشور یکی است:</label>
        <input type="checkbox" name="same_nationality" id="same_nationality"/>

        <label for="availability"> فقط گوشی های که موجود هستند </label>
        <input type="checkbox" name="availability" id="availability"/>

        <button type="submit"> فیلتر</button>
        <button type="submit"><a href="{% url 'phone-list-page' %}">بازنشانی فیلتر</a></button>

    </form>
</div>

<button><a href="{% url 'phone-form-page' %}">اضافه کردن محصول جدید</a></button>
{% render_table table %}

<script src="{% static 'js/custom-home.js' %}"></script>
</body>
</html>